# Generated by Django 4.2.2 on 2023-07-06 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_date_created_question_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='question.question')),
            ],
        ),
    ]
